version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: cocoindex
      POSTGRES_USER: cocoindex
      POSTGRES_PASSWORD: cocoindex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cocoindex -d cocoindex"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
